FROM buymybm100/x11

RUN sudo add-apt-repository ppa:webupd8team/java -y && \
    echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections && \
     apt-get -y update  && \
     apt-get -y install oracle-java8-installer && \
     apt-get -y install oracle-java8-set-default 

